--------------------------------------------------------
--  File created - Sunday-May-13-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANTRENAMENT
--------------------------------------------------------

  CREATE TABLE "ALEXIONUT"."ANTRENAMENT" 
   (	"ID_ANTRENAMENT" NUMBER(*,0), 
	"INTENSITATE" VARCHAR2(1 BYTE), 
	"DENSITATE" VARCHAR2(4 BYTE), 
	"VOLUM" VARCHAR2(25 BYTE), 
	"FRECVENTA" VARCHAR2(1 BYTE), 
	"CONTINUT" BLOB, 
	"NUME_ANTR" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTINUT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ALEXIONUT.ANTRENAMENT
SET DEFINE OFF;
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001511,'1','1','1','1','sedentarEctomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001521,'1','1','1','1','sedentarMesomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001531,'1','1','1','1','sedentarEndomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001512,'1','1','1','1','semiActivEctomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001522,'1','1','1','1','semiActivMesomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001532,'1','1','1','1','semiActivEndomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001513,'1','1','1','1','activEctomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001523,'1','1','1','1','activMesomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001533,'1','1','1','1','activEndomorfLowStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001111,'1','1','1','1','sedentarEctomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001121,'1','1','1','1','sedentarMesomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001131,'1','1','1','1','sedentarEndomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001112,'1','1','1','1','semiActivEctomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001122,'1','1','1','1','semiActivMesomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001132,'1','1','1','1','semiActivEndomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001113,'1','1','1','1','activEctomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001123,'1','1','1','1','activMesomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001133,'1','1','1','1','activEndomorfMidStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001011,'1','1','1','1','sedentarEctomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001021,'1','1','1','1','sedentarMesomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001031,'1','1','1','1','sedentarEndomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001012,'1','1','1','1','semiActivEctomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001022,'1','1','1','1','semiActivMesomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001032,'1','1','1','1','semiActivEndomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001013,'1','1','1','1','activEctomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001023,'1','1','1','1','activMesomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10001033,'1','1','1','1','activEndomorfHighStressSlabire');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010511,'1','1','1','1','sedentarEctomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010521,'1','1','1','1','sedentarMesomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010531,'1','1','1','1','sedentarEndomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010512,'1','1','1','1','semiActivEctomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010522,'1','1','1','1','semiActivMesomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010532,'1','1','1','1','semiActivEndomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010513,'1','1','1','1','activEctomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010523,'1','1','1','1','activMesomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010533,'1','1','1','1','activEndomorfLowStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010111,'1','1','1','1','sedentarEctomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010121,'1','1','1','1','sedentarMesomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010131,'1','1','1','1','sedentarEndomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010112,'1','1','1','1','semiActivEctomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010122,'1','1','1','1','semiActivMesomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010132,'1','1','1','1','semiActivEndomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010113,'1','1','1','1','activEctomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010123,'1','1','1','1','activMesomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010133,'1','1','1','1','activEndomorfMidStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010011,'1','1','1','1','sedentarEctomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010021,'1','1','1','1','sedentarMesomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010031,'1','1','1','1','sedentarEndomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010012,'1','1','1','1','semiActivEctomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010022,'1','1','1','1','semiActivMesomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010032,'1','1','1','1','semiActivEndomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010013,'1','1','1','1','activEctomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010023,'1','1','1','1','activMesomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (10010033,'1','1','1','1','activEndomorfHighStressHipertrofie');
Insert into ALEXIONUT.ANTRENAMENT (ID_ANTRENAMENT,INTENSITATE,DENSITATE,VOLUM,FRECVENTA,NUME_ANTR) values (-1,'1','1','1','1','Nu sunteti apt de sport.');
--------------------------------------------------------
--  DDL for Index BIN$ReFcIe+UTviYM87zhgzGiw==$0
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALEXIONUT"."BIN$ReFcIe+UTviYM87zhgzGiw==$0" ON "ALEXIONUT"."ANTRENAMENT" ("ID_ANTRENAMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANTRENAMENT
--------------------------------------------------------

  ALTER TABLE "ALEXIONUT"."ANTRENAMENT" ADD PRIMARY KEY ("ID_ANTRENAMENT")
  USING INDEX (CREATE UNIQUE INDEX "ALEXIONUT"."BIN$ReFcIe+UTviYM87zhgzGiw==$0" ON "ALEXIONUT"."ANTRENAMENT" ("ID_ANTRENAMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "ALEXIONUT"."ANTRENAMENT" MODIFY ("ID_ANTRENAMENT" NOT NULL ENABLE);
