--------------------------------------------------------
--  File created - Monday-May-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXERCITIU
--------------------------------------------------------

  CREATE TABLE "ALEXIONUT"."EXERCITIU" 
   (	"ID_EXERCITIU" NUMBER(38,0), 
	"DENUMIRE_EXERCITIU" VARCHAR2(40 BYTE), 
	"POZA_INCEPUT" BLOB, 
	"POZA_SFARSIT" BLOB, 
	"DESCRIERE" VARCHAR2(300 BYTE), 
	"GRUPA_MUSCULARA" VARCHAR2(50 BYTE), 
	"REPETARI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("POZA_INCEPUT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("POZA_SFARSIT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ALEXIONUT.EXERCITIU
SET DEFINE OFF;
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (29,'Leverage Iso Row',null,'Back','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (36,'
Burpee Pull-Up',null,'Back','5 sets ,5 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (45,'Standing Calf Raises',null,'Legs','4 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (52,'Weighted Bench Dip',null,'Triceps','4 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (60,'Elbow to Knee',null,'Abs','3 sets ,15 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (67,'Incline Hammer Curls',null,'Biceps','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (72,'Jogging-Treadmill',null,'Cardio','10 Minutes');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (73,'Jogging-Treadmill',null,'Cardio','20 Minutes');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (74,'Jogging-Treadmill',null,'Cardio','50 Minutes');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (75,'Rest',null,null,null);
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (4,'Smith Machine Shrug',null,'Traps','4 sets , 20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (5,'Leverage Shrug',null,'Traps','4 sets , 20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (6,'Standing Military Press',null,'Shoulders','5 sets , 5 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (7,'One-Arm Side Laterals',null,'Shoulders','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (8,'Power Partials',null,'Shoulders','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (9,'Seated Dumbbell Press',null,'Shoulders','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (10,'Reverse Flyes',null,'Shoulders','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (11,'Dumbbell One-Arm Rear Lateral Raise',null,'Shoulders','4 sets ,10 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (12,'Car Drivers',null,'Shoulders','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (13,'Front Plate Raise',null,'Shoulders','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (14,'Side Lateral Raise',null,'Shoulders','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (15,'Face Pull',null,'Shoulders','4 sets ,10 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (16,'Dumbbell Bench Press',null,'Chest','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (17,'Pushups',null,'Chest','4 sets ,15 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (18,'Dumbbell Flyes',null,'Chest','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (19,'Incline Dumbbell Press',null,'Chest','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (20,'Bodyweight Flyes',null,'Chest','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (21,'Incline Cable Flye',null,'Chest','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (22,'Incline Push-Up',null,'Chest','3 sets ,15 reps
');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (23,'Barbell Incline Bench Press Medium-Grip',null,'Chest','4 sets ,8 reps
');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (24,'Leverage Incline Chest Press',null,'Chest','4 sets ,10 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (25,'Straight-Arm Dumbbell Pullover',null,'Chest','4 sets ,10 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (26,'
Leverage Decline Chest Press',null,'Chest','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (27,'V-Bar Pulldown',null,'Back','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (28,'Wide-Grip Lat Pulldown',null,'Back','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (30,'Straight-Arm Pulldown',null,'Back','3 sets ,10 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (31,'Elevated Cable Rows',null,'Back','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (32,'
Seated Cable Rows',null,'Back','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (33,'Alternating Renegade Row',null,'Back','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (34,'Hyperextensions (Back Extensions)',null,'Back','3 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (35,'Superman',null,'Back','3 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (37,'Single-Leg Press',null,'Legs','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (38,'Barbell Full Squat',null,'Legs','5 sets ,5 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (39,'Front Squats With Two Kettlebells',null,'Legs','3 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (40,'Rope Jumping',null,'Legs','5 minutes');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (42,'Romanian Deadlift With Dumbbells',null,'Legs','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (43,'
Lying Leg Curls',null,'Legs','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (44,'Smith Machine Calf Raise',null,'Legs','4 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (46,'Thigh Adductor',null,'Legs','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (47,'Thigh Abductor',null,'Legs','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (48,'Dips - Triceps Version',null,'Triceps','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (49,'Decline EZ Bar Triceps Extension',null,'Triceps','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (50,'Close-Grip Barbell Bench Press',null,'Triceps','5 sets ,5 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (51,'Triceps Pushdown - V-Bar Attachment',null,'Triceps','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (53,'Kneeling Cable Triceps Extension',null,'Triceps','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (54,'EZ-Bar Skullcrusher',null,'Triceps','4 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (55,'Cable Lying Triceps Extension',null,'Triceps','3 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (56,'Lying Dumbbell Tricep Extension',null,'Triceps','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (57,'Suspended Fallout',null,'Abs','4 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (58,'Decline Reverse Crunch',null,'Abs','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (59,'Spider Crawl',null,'Abs','3 sets ,15 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (61,'Cocoons',null,'Abs','3 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (62,'Plate Twist',null,'Abs','4 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (63,'Decline Crunch',null,'Abs','3 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (64,'Exercise Ball Pull-In',null,'Abs','3 sets ,20 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (65,'Barbell Ab Rollout',null,'Abs','3 sets ,8 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (66,'Reverse Crunch',null,'Abs','3 sets ,15 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (68,'Wide-Grip Standing Barbell Curl',null,'Biceps','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (69,'Spider Curl',null,'Biceps','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (70,'EZ-Bar Curl',null,'Biceps','4 sets ,12 reps');
Insert into ALEXIONUT.EXERCITIU (ID_EXERCITIU,DENUMIRE_EXERCITIU,DESCRIERE,GRUPA_MUSCULARA,REPETARI) values (71,'Hammer Curls',null,'Biceps','4 sets ,10 reps');
--------------------------------------------------------
--  DDL for Index SYS_C0010848
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALEXIONUT"."SYS_C0010848" ON "ALEXIONUT"."EXERCITIU" ("ID_EXERCITIU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EXERCITIU
--------------------------------------------------------

  ALTER TABLE "ALEXIONUT"."EXERCITIU" ADD PRIMARY KEY ("ID_EXERCITIU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_EXERCITIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ALEXIONUT"."TRIGGER_EXERCITIU" 
BEFORE INSERT ON exercitiu
FOR EACH ROW
BEGIN
IF :new.id_exercitiu IS NULL THEN 
SELECT exercitiu_SEQ.NEXTVAL
INTO :new.id_exercitiu
FROM dual;
END IF;
END;
/
ALTER TRIGGER "ALEXIONUT"."TRIGGER_EXERCITIU" ENABLE;
